# Generated by Django 5.2.14 on 2026-05-23 16:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo_owner", models.CharField(max_length=255)),
                ("repo_name", models.CharField(max_length=255)),
                ("head_ref", models.CharField(max_length=255)),
                ("base_ref", models.CharField(max_length=255)),
                ("pr_number", models.IntegerField(blank=True, null=True)),
                ("pr_opened_at", models.DateTimeField(blank=True, null=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repo_owner", "repo_name", "head_ref"),
                        name="uniq_workspace_repo_head",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("pr_number__isnull", False)),
                        fields=("repo_owner", "repo_name", "pr_number"),
                        name="uniq_workspace_repo_pr",
                    ),
                ],
            },
        ),
    ]
