# Generated by Django 5.2.14 on 2026-05-23 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_json', models.TextField(default='{}')),
                ('etag', models.CharField(max_length=36)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storyline_updates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storyline', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'storyline',
            },
        ),
        migrations.CreateModel(
            name='StorylineFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diff_file_path', models.CharField(max_length=1024)),
                ('order_index', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('storyline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspaces.storyline')),
            ],
            options={
                'db_table': 'storyline_file',
                'ordering': ['order_index'],
                'constraints': [models.UniqueConstraint(fields=('storyline', 'diff_file_path'), name='uniq_storyline_file_path')],
            },
        ),
    ]
