# Generated by Django 5.2.14 on 2026-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_drop_storyline_raw_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
