# Generated by Django 5.2.14 on 2026-05-31 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0005_workspace_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storylinefile",
            name="title",
        ),
    ]
