/* data-v2.jsx — expanded with local/public split and branch entities */

const BRANCHES_V2 = [
  /* ──────────────── BRANCHES (no workspace yet) ──────────────── */
  {
    kind: 'branch',
    id: 'br-edge-cases',
    branch: 'experiment/edge-cases',
    author: 'You',
    base: 'main',
    ahead: 2, behind: 0,
    added: 31, removed: 14,
    updated: '5m ago',
    lastCommit: 'try alternative rounding for sub-cent totals',
  },
  {
    kind: 'branch',
    id: 'br-docs-typos',
    branch: 'docs/api-typos',
    author: 'You',
    base: 'main',
    ahead: 1, behind: 4,
    added: 12, removed: 8,
    updated: 'yesterday',
    lastCommit: 'fix typos in webhook docs',
  },
  {
    kind: 'branch',
    id: 'br-mira-cache',
    branch: 'mira/cache-key-fix',
    author: 'Mira Park',
    base: 'main',
    ahead: 3, behind: 0,
    added: 18, removed: 6,
    updated: '3h ago',
    lastCommit: 'include user-locale in cache key',
  },

  /* ──────────────── LOCAL REVIEW (workspace, no PR yet) ──────────────── */
  {
    kind: 'local',
    id: 'ws-stripe-webhook',
    branch: 'fix/stripe-webhook-retry',
    title: 'Idempotent retries for Stripe webhook handler',
    author: 'You',
    base: 'main',
    ahead: 3, behind: 0,
    added: 64, removed: 22,
    files: 4,
    updated: '12 min ago',
    state: 'draft',
    storyline: 0,
    comments: 0,
    reviewers: [],
    summary: 'Wraps the webhook handler in an idempotency check using the Stripe event id.',
  },
  {
    kind: 'local',
    id: 'ws-eslint-bump',
    branch: 'tooling/eslint-bump',
    title: 'Bump ESLint to 9 + fix new rule violations',
    author: 'You',
    base: 'main',
    ahead: 1, behind: 2,
    added: 142, removed: 138,
    files: 23,
    updated: '1h ago',
    state: 'local-ready',
    storyline: 3,
    comments: 0,
    reviewers: [],
    summary: 'Mostly mechanical. Storyline groups the manual fixes that need a real look.',
  },

  /* ──────────────── PUBLIC REVIEW (GitHub PR open) ──────────────── */
  {
    kind: 'public',
    id: 'ws-checkout-v2',
    branch: 'feat/checkout-v2',
    title: 'Replace legacy checkout with multi-step flow',
    author: 'You',
    base: 'main',
    ahead: 14, behind: 2,
    added: 412, removed: 87,
    files: 11,
    updated: 'just now',
    state: 'in-review',
    prNumber: 482,
    prState: 'open',
    storyline: 7,
    comments: 6,
    reviewers: ['Mira Park', 'Jon Singh'],
    checks: { pass: 8, fail: 0, pending: 1 },
  },
  {
    kind: 'public',
    id: 'ws-dashboard-perf',
    branch: 'mira/dashboard-perf',
    title: 'Memoize dashboard widgets; drop redundant fetches',
    author: 'Mira Park',
    base: 'main',
    ahead: 6, behind: 1,
    added: 138, removed: 96,
    files: 8,
    updated: '2h ago',
    state: 'reviewing',
    prNumber: 481,
    prState: 'open',
    storyline: 5,
    comments: 3,
    reviewers: ['You', 'Sam Okafor'],
    checks: { pass: 8, fail: 0, pending: 0 },
  },
  {
    kind: 'public',
    id: 'ws-sso-okta',
    branch: 'jon/sso-okta',
    title: 'Okta SSO provider behind feature flag',
    author: 'Jon Singh',
    base: 'main',
    ahead: 22, behind: 4,
    added: 731, removed: 14,
    files: 19,
    updated: 'yesterday',
    state: 'requested',
    prNumber: 479,
    prState: 'open',
    storyline: 9,
    comments: 11,
    reviewers: ['You'],
    checks: { pass: 7, fail: 1, pending: 0 },
  },
  {
    kind: 'public',
    id: 'ws-empty-states',
    branch: 'sam/empty-states-polish',
    title: 'Empty state illustrations + copy pass',
    author: 'Sam Okafor',
    base: 'main',
    ahead: 4, behind: 0,
    added: 92, removed: 38,
    files: 6,
    updated: 'Mon',
    state: 'approved',
    prNumber: 478,
    prState: 'open',
    storyline: 3,
    comments: 2,
    reviewers: ['You', 'Mira Park'],
    checks: { pass: 9, fail: 0, pending: 0 },
  },
];

/* External PRs — open on GitHub, no Stage workspace.
   You either opened them outside Stage, or someone asked you to review one. */
const EXTERNAL_PRS = [
  /* By you (opened on github.com, never imported) */
  {
    id: 'ext-readme-rewrite',
    role: 'author',
    branch: 'docs/readme-rewrite',
    title: 'Rewrite README onboarding section',
    author: 'You',
    base: 'main',
    added: 84, removed: 71,
    files: 2,
    updated: '6h ago',
    prNumber: 483,
    state: 'in-review',
    reviewers: ['Mira Park'],
    checks: { pass: 9, fail: 0, pending: 0 },
  },
  /* Awaiting your review */
  {
    id: 'ext-otel-spans',
    role: 'reviewer',
    branch: 'sam/otel-spans',
    title: 'Add OpenTelemetry spans to checkout API',
    author: 'Sam Okafor',
    base: 'main',
    added: 234, removed: 9,
    files: 5,
    updated: '40m ago',
    prNumber: 484,
    state: 'in-review',
    reviewers: ['You', 'Mira Park'],
    checks: { pass: 8, fail: 0, pending: 1 },
  },
  {
    id: 'ext-bot-deps',
    role: 'reviewer',
    branch: 'dependabot/lockfile',
    title: 'Bump 12 transitive deps (lockfile only)',
    author: 'dependabot',
    base: 'main',
    added: 412, removed: 380,
    files: 1,
    updated: '2d ago',
    prNumber: 477,
    state: 'in-review',
    reviewers: ['You'],
    checks: { pass: 9, fail: 0, pending: 0 },
  },
];

Object.assign(window, { BRANCHES_V2, EXTERNAL_PRS });
